### ISSUE TITLE
Get jQuery and jQuery Git Migrate from local files

### ISSUE THREAD

**Issue by astagi** [leanderiversen/version-control-for-jquery#3]
Hi @leanderiversen is there a way to get jQuery and jQuery Git Migrate from local files instead of CDN using your plugin?

Thank you in advance,

AS

**Comment by leanderiversen** [comment]
Hi,

Thank you for your question!

This is not achievable using the plugin, and there are no plans to add this functionality.

I would suggest that the local files are enqueued directly in the code to override the default paths.

I hope that makes sense.

All the best,
Leander Iversen
